---
abstract: 'Perl based solution for controlled network access'
author:
  - 'Karl Gaissmaier <gaissmai (at) cpan.org>'
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Captive-Portal
provides:
  Captive::Portal:
    file: lib/Captive/Portal.pm
    version: 2.10
  Captive::Portal::Role::AuthenSimple:
    file: lib/Captive/Portal/Role/AuthenSimple.pm
    version: 2.10
  Captive::Portal::Role::Config:
    file: lib/Captive/Portal/Role/Config.pm
    version: 2.10
  Captive::Portal::Role::Firewall:
    file: lib/Captive/Portal/Role/Firewall.pm
    version: 2.10
  Captive::Portal::Role::Locking:
    file: lib/Captive/Portal/Role/Locking.pm
    version: 2.10
  Captive::Portal::Role::Session:
    file: lib/Captive/Portal/Role/Session.pm
    version: 2.10
  Captive::Portal::Role::Utils:
    file: lib/Captive/Portal/Role/Utils.pm
    version: 2.10
  Captive::Portal::TestServer:
    file: lib/Captive/Portal/TestServer.pm
    version: 2.10
recommends:
  Authen::Simple::RADIUS: 0
  HTTP::Server::Simple::CGI: 0
  HTTP::Server::Simple::Static: 0
  Test::WWW::Mechanize::CGI: 0
requires:
  Authen::Simple: 0
  CGI::Cookie: 0
  CGI::Fast: 0
  Capture::Tiny: 0
  JSON: 0
  Log::Dispatch::Syslog: 0
  Log::Log4perl: 0
  Role::Basic: 0
  Scalar::Util: 0
  Template: 0
  Time::HiRes: 0
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.10
